import React, { useEffect, useState } from 'react';
import { Crown, Medal, Trophy } from 'lucide-react';
import AnimatedBackground from '../components/AnimatedBackground';
import Footer from '../components/Footer';
import { apiUrl } from '../config';
import { getStoredUser } from '../utils/auth';
interface LeaderboardUser { username: string; solvedCount: number; rank?: number; }
const LeaderboardPage: React.FC = () => {
  const [users, setUsers] = useState<LeaderboardUser[]>([]); const [loading, setLoading] = useState(true); const [currentUser, setCurrentUser] = useState<string | null>(null);
  useEffect(() => { (async () => { try { const res = await fetch(apiUrl('/api/auth/leaderboard')); const data = await res.json(); if (res.ok) setUsers(data); setCurrentUser(getStoredUser()?.username || null); } catch (error) { console.error('Failed to fetch leaderboard', error); } finally { setLoading(false); } })(); }, []);
  const medal = (index: number, rank: number) => index === 0 ? <span className="grid place-items-center"><Crown size={21} className="fill-amber-400 text-amber-500"/><small>#{rank}</small></span> : index < 3 ? <span className="grid place-items-center"><Medal size={20} className={index === 1 ? 'fill-slate-300 text-slate-400' : 'fill-amber-700 text-amber-700'}/><small>#{rank}</small></span> : <span className="font-mono text-sm font-medium text-slate-500">#{rank}</span>;
  return <div className="page-shell"><AnimatedBackground/><main className="page-wrap max-w-5xl py-10 sm:py-14"><header className="border-b border-slate-200/80 pb-10 dark:border-white/10"><p className="eyebrow mb-4"><Trophy size={14}/> Community progress</p><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 className="text-4xl font-extrabold tracking-[-.045em] text-[#102b27] sm:text-5xl dark:text-white">Leaderboard</h1><p className="mt-3 max-w-xl text-slate-600 dark:text-slate-400">A live view of the learners building consistency, one problem at a time.</p></div><p className="font-mono text-sm text-slate-500">Top {users.length || '—'} learners</p></div></header>{loading ? <div className="mt-8 space-y-3">{Array.from({length: 6}).map((_, i) => <div key={i} className="surface h-[76px] animate-pulse rounded-2xl"/>)}</div> : <section className="surface mt-8 overflow-hidden rounded-2xl"><div className="grid grid-cols-[66px_1fr_auto] gap-4 border-b border-slate-200/80 px-5 py-3 text-[11px] font-extrabold uppercase tracking-[.16em] text-slate-400 dark:border-white/10 sm:px-7"><span className="text-center">Rank</span><span>Developer</span><span>Solved</span></div><div>{users.map((user, index) => { const rank = user.rank ?? index + 1; const isCurrent = user.username === currentUser; return <div key={user.username} className={`grid grid-cols-[66px_1fr_auto] items-center gap-4 border-b border-slate-100 px-5 py-4 last:border-0 dark:border-white/[.06] sm:px-7 ${isCurrent ? 'bg-teal-50/70 dark:bg-teal-400/[.06]' : 'hover:bg-slate-50/70 dark:hover:bg-white/[.025]'}`}><div className="text-center [&_small]:mt-0.5 [&_small]:block [&_small]:text-[10px] [&_small]:font-bold [&_small]:text-slate-400">{medal(index, rank)}</div><div className="flex items-center gap-3"><span className={`grid h-10 w-10 place-items-center rounded-full text-sm font-extrabold ${index === 0 ? 'bg-amber-100 text-amber-800' : 'bg-[#dceee9] text-[#123b36] dark:bg-teal-400/10 dark:text-teal-300'}`}>{user.username.charAt(0).toUpperCase()}</span><p className="font-bold">{user.username}{isCurrent && <span className="ml-2 rounded-full bg-teal-100 px-2 py-0.5 text-[10px] font-extrabold uppercase tracking-wider text-teal-800 dark:bg-teal-400/10 dark:text-teal-300">You</span>}</p></div><span className="font-mono text-sm font-medium text-[#123b36] dark:text-teal-300">{user.solvedCount}<span className="ml-1 text-[10px] font-sans font-bold uppercase text-slate-400">Qs</span></span></div>; })}</div></section>}</main><Footer/></div>;
};
export default LeaderboardPage;
