import React, { useEffect, useState } from 'react';
import { ArrowRight, Filter, Search } from 'lucide-react';
import { Link } from 'react-router-dom';
import AnimatedBackground from '../components/AnimatedBackground';
import Footer from '../components/Footer';
import { defaultTopics, getTopicIcon, type TopicDefinition } from '../data/topics';
import { fetchPublicTopics } from '../utils/topicApi';

const difficultyStyle: Record<string, string> = { Easy: 'bg-emerald-50 text-emerald-700 dark:bg-emerald-400/10 dark:text-emerald-300', Medium: 'bg-amber-50 text-amber-700 dark:bg-amber-400/10 dark:text-amber-300', Hard: 'bg-rose-50 text-rose-700 dark:bg-rose-400/10 dark:text-rose-300' };
const TopicsPage: React.FC = () => {
  const [searchQuery, setSearchQuery] = useState(''); const [selectedDifficulty, setSelectedDifficulty] = useState<string | null>(null); const [topics, setTopics] = useState<TopicDefinition[]>([]); const [loading, setLoading] = useState(true);
  useEffect(() => { fetchPublicTopics().then(setTopics).catch(() => setTopics(defaultTopics)).finally(() => setLoading(false)); }, []);
  const shown = topics.filter(({ name, difficulty }) => name.toLowerCase().includes(searchQuery.toLowerCase()) && (!selectedDifficulty || difficulty === selectedDifficulty));
  return <div className="page-shell"><AnimatedBackground /><main className="page-wrap py-10 sm:py-14">
    <div className="grid gap-8 border-b border-slate-200/80 pb-10 dark:border-white/10 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="eyebrow mb-4">The practice library</p><h1 className="text-4xl font-extrabold tracking-[-.045em] text-[#102b27] sm:text-5xl dark:text-white">Find your next pattern.</h1><p className="mt-4 max-w-xl text-slate-600 dark:text-slate-400">A deliberate collection of core data structure and algorithm topics, organized for steady progress.</p></div><p className="font-mono text-sm text-slate-500">{topics.length || '—'} tracks available</p></div>
    <div className="surface mt-8 flex flex-col gap-3 rounded-2xl p-3 sm:flex-row"><label className="relative block flex-1"><Search size={18} className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400"/><input value={searchQuery} onChange={e => setSearchQuery(e.target.value)} placeholder="Search topics" className="w-full rounded-xl border-0 bg-slate-100/80 py-3 pl-11 pr-4 text-sm font-medium outline-none ring-0 placeholder:text-slate-400 focus:bg-slate-100 dark:bg-white/5 dark:text-white dark:focus:bg-white/10"/></label><div className="flex gap-2 overflow-x-auto">{['Easy','Medium','Hard'].map(diff => <button onClick={() => setSelectedDifficulty(selectedDifficulty === diff ? null : diff)} key={diff} className={`rounded-xl px-4 py-3 text-sm font-bold transition ${selectedDifficulty === diff ? 'bg-[#123b36] text-white dark:bg-teal-400 dark:text-[#08241f]' : 'text-slate-500 hover:bg-slate-100 dark:hover:bg-white/5'}`}>{diff}</button>)}</div></div>
    {loading ? <div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{Array.from({length: 6}).map((_, i) => <div key={i} className="surface h-56 animate-pulse rounded-2xl"/>)}</div> : <><div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{shown.map(topic => <Link key={topic.id || topic.slug} to={`/topic/${topic.slug}`} className="surface group flex min-h-[225px] flex-col rounded-2xl p-6 transition duration-300 hover:-translate-y-1 hover:border-teal-600/30 hover:shadow-xl hover:shadow-teal-950/5"><div className="flex items-start justify-between"><span className="grid h-11 w-11 place-items-center rounded-xl bg-[#dceee9] text-[#123b36] transition group-hover:bg-[#123b36] group-hover:text-white dark:bg-teal-400/10 dark:text-teal-300">{getTopicIcon(topic.iconKey)}</span><span className={`rounded-full px-2.5 py-1 text-[11px] font-extrabold ${difficultyStyle[topic.difficulty]}`}>{topic.difficulty}</span></div><h2 className="mt-6 text-lg font-extrabold">{topic.name}</h2><p className="mt-2 text-sm leading-6 text-slate-500 dark:text-slate-400">{topic.description}</p><div className="mt-auto flex items-center justify-between border-t border-slate-100 pt-5 text-sm font-bold dark:border-white/10"><span className="text-slate-500">{topic.problemCount || 0} problems</span><span className="flex items-center gap-1 text-teal-700 opacity-0 transition group-hover:opacity-100 dark:text-teal-300">Open <ArrowRight size={15}/></span></div></Link>)}</div>{!shown.length && <div className="py-24 text-center"><span className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-slate-100 text-slate-400 dark:bg-white/5"><Filter size={20}/></span><h2 className="mt-4 font-extrabold">No matching topics</h2><p className="mt-1 text-sm text-slate-500">Try another search or difficulty.</p></div>}</>}
  </main><Footer /></div>;
};
export default TopicsPage;
